AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation Template For Craeting EKS Control plan, worker nodes"


Parameters:

  env:
    Type: String
    Description: Deployment Environment
    Default: "devl"
  
  awsAcct:
    Type: String
    Description: "AWS Account Number"
    Default: "569781470788"
  
  componentValue:
    Type: String
    Default: "ae-collibra-dq"
  
  clusterName:
    Type: String
    Default: "gulshan-eks-cluster"

  PublicSubnet1:
    Type: String
    Default: "subnet-04258bdeed32d8f64"
  
  PublicSubnet2:
    Type: String
    Default: "subnet-0a412f09e68c1f182"
  
  # privateSubnet0:
  #   Type: String
  #   Default: "subnet-01fd2c2546efad5f6"
  
  # privateSubnet1:
  #   Type: String
  #   Default: "subnet-01f4f14af82e13c40"

Resources:

  EKSNodeGroup:
    Type: AWS::EKS::Nodegroup
    DependsOn:
      - EKSCluster
    Properties:
      NodegroupName: !Join [ "-", [ !Ref env , !Ref clusterName , "node-group" ] ]
      ClusterName: !Join [ "-", [ !Ref env , !Ref clusterName ] ]
      AmiType: AL2_x86_64
      CapacityType: ON_DEMAND
      DiskSize: 200
      ForceUpdateEnabled: false
      InstanceTypes:
      - t3.medium            #r6i.4xlarge
      NodeRole: !Join [":", ["arn:aws:iam:" , !Ref awsAcct , "role/nodedemorolegulshan"]]
      ScalingConfig:
        DesiredSize: 2
        MaxSize: 8
        MinSize: 2

      Subnets:
        - !Ref PublicSubnet2
        - !Ref PublicSubnet1
      

      UpdateConfig:
        MaxUnavailablePercentage: 50
      Tags: 
        Name: !Join [ "-", [ !Ref env , !Ref clusterName ] ]
        component: !Ref componentValue

