apiVersion: v1
kind: Service
metadata:
  name: deployment-nodeport-service


spec:
  type: NodePort
  selector:
    app: Gulapp
  ports:
    - name: http
      port: 80
      targetPort: 80
      NodePort: 31233