
name: Complete Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The application deployment environment'
        default: 'devl'
        required: true
        type: choice
        options:
         - devl
         - prod

jobs:
  Deploy:
    runs-on: ubuntu-latest
    #this is for control the deployment via approval method 1
    # alrerady craeted env with name dev in github setings 
    # environment: Infra

    
    steps:
     
    - name: Checkout
      uses: actions/checkout@v2
      
#      # For mannual approval method 2 
#     - uses: trstringer/manual-approval@v1
#       with:
#         approvers: gulshan3798
          

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region: us-east-1

        

    - name: "Set environment variables for devl environment"
      if: ${{ github.event.inputs.environment == 'devl' }}
      run: |
        echo "ENVIRONMENT=devl" >> $GITHUB_ENV
        echo "AWS_ACCT=620423771455" >> $GITHUB_ENV

    - name: "Set environment variables for prod environment"
      if: ${{ github.event.inputs.environment == 'prod' }}
      run: |
        echo "ENVIRONMENT=prod" >> $GITHUB_ENV
        echo "AWS_ACCT=188549407646" >> $GITHUB_ENV

    - name: run-ecr 
      run: |
       aws cloudformation deploy --stack-name RoleStack-${{ env.ENVIRONMENT }} --template-file ${{ env.ENVIRONMENT }}-role-eks-node.yml --tags Name=eks-role-stack-${{ env.ENVIRONMENT }} --region us-east-1 --capabilities CAPABILITY_NAMED_IAM
       aws cloudformation deploy --stack-name NetworkStack-${{ env.ENVIRONMENT }} --template-file ${{ env.ENVIRONMENT }}-aws-infra-vpc.yml --tags Name=eks-network-stack-${{ env.ENVIRONMENT }} --region us-east-1
       aws cloudformation deploy --stack-name EKS-deploy-${{ env.ENVIRONMENT }} --template-file ${{ env.ENVIRONMENT }}-aws-infra-eks.yml --tags Name=eks-stack-${{ env.ENVIRONMENT }} --region us-east-1
