name: Role Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The application deployment environment'
        default: 'devl'
        required: true
        type: choice
        options:
         - devl
         - prod

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:    
    - name: Checkout
      uses: actions/checkout@v2
          
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region: us-east-1 

    - name: "Set environment variables for devl environment"
      if: ${{ github.event.inputs.environment == 'devl' }}
      run: |
        echo "ENVIRONMENT=devl" >> $GITHUB_ENV
        echo "AWS_ACCT=498614279603" >> $GITHUB_ENV
    - name: "Set environment variables for prod environment"
      if: ${{ github.event.inputs.environment == 'prod' }}

      run: |
        echo "ENVIRONMENT=prod" >> $GITHUB_ENV
        echo "AWS_ACCT=188549407646" >> $GITHUB_ENV
        
    - name: run-ecr 
      run: aws cloudformation deploy --stack-name gul-role-stack-${{ env.ENVIRONMENT }} --template-file ${{ env.ENVIRONMENT }}-role.yml  --tags Name=gul-role-stack-${{ env.ENVIRONMENT }} --region us-east-1
